# remove.packages("GeoPressureR")
# devtools::install_github("rafnuss/GeoPressureR")

suppressMessages({
  library(BiocManager)
  options(repos = BiocManager::repositories())
  library(plotly)
  library(shinyjs)
  library(GeoPressureR)
  library(shiny)
  library(leaflet)
  library(plotly)
  library(rgdal)
  library(leaflet.extras)
  library(raster)
  library(shinyWidgets)
  library(geosphere)
  library(RColorBrewer)
  library(readr)
})

