# remove.packages("GeoPressureR")
# devtools::install_github("rafnuss/GeoPressureR")

suppressMessages({
  library(BiocManager)
  options(repos = BiocManager::repositories())
  library(plotly)
  library(shinyjs)
  library(GeoPressureR)
  library(shiny)
  library(leaflet)
  library(plotly)
  library(terra)
  library(leaflet.extras)
  library(shinyWidgets)
  library(geosphere)
  library(RColorBrewer)
})
