#' Create a path from indices of coordinate
#'
#' Convert the 2D coordinate index of a map and produce a path data.frame. This function is used by
#' `map2path`, `graph_most_likely`, `graph_simulation` and `geopressureviz`.
#'
#' @param ind index in the 2D map (vector or matrix)
#' @param tag_graph either a `tag` or a `graph` which contains both `stap`, `extent` and
#' `scale`.
#' @param .use_known If true, enforce the known position in the path created
#' (approx. to the map resolution).
#' @return A path data.frame
#' - `stap_id` stationary period
#' - `ind` indices of the coordinate in the 2D grid. Useful to retrieve map or graph information.
#' - `lat` Latitude,
#' - `lon` longitude
#' @examples
#' setwd(system.file("extdata/", package = "GeoPressureR"))
#' tag <- tag_create("18LX") |> tag_label()
#' tag <- tag_create(tag, c(-16, 23, 0, 50), scale = 1)
#'
#' # ind generated by `graph_most_likely`
#' ind <- c(1652, 1603, 1755, 1708, 1607)
#' path <- ind2path(ind, tag)
#' str(path)
#'
#' # ind generated by `graph_simulation`
#' ind <- matrix(c(
#'   1652, 1652, 1652, 1652, 1652, 1652, 1652, 1652, 1652, 1652,
#'   1653, 1606, 1653, 1504, 1604, 1704, 1504, 1653, 1753, 1701,
#'   1805, 1457, 1408, 1657, 1609, 1903, 1506, 1757, 1856, 1804,
#'   1607, 1514, 1611, 1457, 1860, 1802, 1759, 1609, 1760, 1208,
#'   1505, 1314, 1559, 1357, 1758, 1852, 1661, 1706, 1862, 1358
#' ), nrow = 10)
#' path <- ind2path(ind, tag)
#' str(path)
#' @export
ind2path <- function(ind,
                     tag_graph) {
  assertthat::assert_that(is.list(tag_graph))
  assertthat::assert_that(assertthat::has_name(tag_graph, "stap"))
  stap <- tag_graph$stap
  assertthat::assert_that(is.data.frame(stap))
  assertthat::assert_that(assertthat::has_name(stap, "stap_id"))
  assertthat::assert_that(assertthat::has_name(stap, "known_lat"))
  assertthat::assert_that(assertthat::has_name(stap, "known_lon"))
  assertthat::assert_that(assertthat::has_name(stap, "include"))

  stap$known <- !is.na(stap$known_lat)
  stap <- stap[, -which(names(stap) %in% c("known_lat", "known_lon"))]

  # Compute the grid information
  assertthat::assert_that(assertthat::has_name(tag_graph, "scale"))
  assertthat::assert_that(assertthat::has_name(tag_graph, "extent"))
  g <- geo_expand(tag_graph$extent, tag_graph$scale)


  # Check path
  assertthat::assert_that(is.numeric(ind))
  assertthat::assert_that(all(prod(g$dim) >= ind[!is.na(ind)]))
  if (is.vector(ind)) {
    ind <- matrix(ind, nrow = 1)
  }
  assertthat::assert_that(dim(ind)[2] == nrow(stap))

  # Convert the index in 2D grid into 1D lat and lon coordinate
  ind_lat <- ind %% g$dim[1]
  ind_lon <- (ind - ind_lat) / g$dim[1] + 1

  # Create the data.frame with all information
  path0 <- data.frame(
    stap_id = rep(stap$stap_id, each = dim(ind)[1]),
    ind = as.vector(ind),
    lat = g$lat[ind_lat],
    lon = g$lon[ind_lon]
  )

  # Combine with stap
  path <- merge(path0, stap, by = "stap_id", all.x = TRUE)

  # Enforce known position in path
  if (.use_known){

    path$lon[stap$known] <- stap$known_lon[stap$known]
    path$lat[stap$known] <- stap$known_lat[stap$known]

    lon_ind_known <- which.min(abs(g$lon - path$lon[stap$known]))
    lat_ind_known <- which.min(abs(g$lat - path$lat[stap$known]))
    path$ind[stap$known] <- (lon_ind_known - 1) * g$dim[1] + lat_ind_known
  }

  return(path)
}
